### ISSUE TITLE
grafmar1.py traceback on Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by ThatsMassy** [ThatsMassy/Lab_fis_Open#3]
Traceback (most recent call last):
  File "grafmar1.py", line 16, in <module>
    input("\n\n\n Premi Enter per far partire la registrazione dei dati")
  File "<string>", line 0
    
    ^
SyntaxError: unexpected EOF while parsing

**Comment by ThatsMassy** [comment]
Now you can find grafmarlegacy.py, run the file with python and it should work just fine
